<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net6.0-windows;net7.0-windows;net8.0-windows;net9.0-windows;</TargetFrameworks>
		<Description>WPF、WinForms、Blazor 混合应用中的标题栏工具集，实现窗口拖动、关闭等。A title bar toolkit for WPF, WinForms, and Blazor hybrid apps. Enables window dragging, closing, and more.</Description>
		<Authors>九零</Authors>
		<PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
		<PackageProjectUrl>https://github.com/JiuLing-zhang/JiuLing.TitleBarKit</PackageProjectUrl>
		<PackageIcon>nuget_icon.png</PackageIcon>
		<PackageIconUrl />
		<Version>1.0.1</Version>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Copyright>Copyright (c) 2025 九零</Copyright>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\nuget_icon.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-windows'">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0-windows'">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0-windows'">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
	</ItemGroup>

</Project>
